#include "GothOgre_Precompiled.h"
#include "GothOgre_MouseButton.h"

namespace GothOgre
{
	GOTHOGRE_IMPLEMENT_ENUM_IO( MouseButton )
		GOTHOGRE_IMPLEMENT_ENUM_IO_CONSTANT2( LEFT,    "Left" )
		GOTHOGRE_IMPLEMENT_ENUM_IO_CONSTANT2( RIGHT,   "Right" )
		GOTHOGRE_IMPLEMENT_ENUM_IO_CONSTANT2( MIDDLE,  "Middle" )
		GOTHOGRE_IMPLEMENT_ENUM_IO_CONSTANT2( BUTTON3, "Button3" )
		GOTHOGRE_IMPLEMENT_ENUM_IO_CONSTANT2( BUTTON4, "Button4" )
		GOTHOGRE_IMPLEMENT_ENUM_IO_CONSTANT2( BUTTON5, "Button5" )
		GOTHOGRE_IMPLEMENT_ENUM_IO_CONSTANT2( BUTTON6, "Button6" )
		GOTHOGRE_IMPLEMENT_ENUM_IO_CONSTANT2( BUTTON7, "Button7" )
	GOTHOGRE_IMPLEMENT_ENUM_IO_END
}