#ifndef GOTHOGRE_MATERIAL_UTIL_H
#define GOTHOGRE_MATERIAL_UTIL_H

#include "GothOgre_Mtl.h"


namespace GothOgre
{
	/** Generating materials by mtl, getting mtl from material. */
	class MaterialUtil
	{
	public:
		/** Generates Ogre material by mtl and additional parameters. */
		static MaterialPtr generateMaterial(const MtlPtr& _mtl, const MatGenParams& _matGenParams);
		
		/** Updates all Ogre materials which were generated by a specified mtl. */
		static void updateAllMaterials(const MtlPtr& _mtl);

		/** Returns mtl which was used to create a specified Ogre material */
		static MtlPtr getMtl(const MaterialPtr& _material);
		static MtlPtr getMtl(const MaterialPtr& _material, MatGenParams& _rMatGenParams);
		static MtlPtr getMtl(const MaterialPtr& _material, MatGenParams* _rMatGenParams);
		static MatGenParams getMatGenParams(const MaterialPtr& _material);
	};

} // namespace GothOgre

#endif // GOTHOGRE_MATERIAL_UTIL_H